#############################################################################
# Makefile for building: aracne
# Generated by qmake (2.01a) (Qt 4.8.7) on: sáb jun 22 15:46:07 2019
# Project:  aracne.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt4/bin/qmake -o Makefile aracne.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -std=c++11 -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/x86_64-linux-gnu/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		aracneui.cpp \
		HTML_Parser.cpp \
		HTTP_Request.cpp \
		HTTP_Response.cpp \
		Proxy_Server.cpp \
		Spider.cpp \
		String_Functions.cpp moc_aracneui.cpp
OBJECTS       = main.o \
		aracneui.o \
		HTML_Parser.o \
		HTTP_Request.o \
		HTTP_Response.o \
		Proxy_Server.o \
		Spider.o \
		String_Functions.o \
		moc_aracneui.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		aracne.pro
QMAKE_TARGET  = aracne
DESTDIR       = 
TARGET        = aracne

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_aracneui.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: aracne.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile aracne.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile aracne.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/aracne1.0.0 || $(MKDIR) .tmp/aracne1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/aracne1.0.0/ && $(COPY_FILE) --parents aracneui.h HTTP_Request.hpp HTTP_Response.hpp Proxy_Server.hpp String_Functions.hpp Spider.hpp HTML_Parser.hpp .tmp/aracne1.0.0/ && $(COPY_FILE) --parents main.cpp aracneui.cpp HTML_Parser.cpp HTTP_Request.cpp HTTP_Response.cpp Proxy_Server.cpp Spider.cpp String_Functions.cpp .tmp/aracne1.0.0/ && $(COPY_FILE) --parents aracneui.ui .tmp/aracne1.0.0/ && (cd `dirname .tmp/aracne1.0.0` && $(TAR) aracne1.0.0.tar aracne1.0.0 && $(COMPRESS) aracne1.0.0.tar) && $(MOVE) `dirname .tmp/aracne1.0.0`/aracne1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/aracne1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_aracneui.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_aracneui.cpp
moc_aracneui.cpp: Proxy_Server.hpp \
		aracneui.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) aracneui.h -o moc_aracneui.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_aracneui.h
compiler_uic_clean:
	-$(DEL_FILE) ui_aracneui.h
ui_aracneui.h: aracneui.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic aracneui.ui -o ui_aracneui.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp HTML_Parser.hpp \
		Spider.hpp \
		Proxy_Server.hpp \
		HTTP_Request.hpp \
		HTTP_Response.hpp \
		String_Functions.hpp \
		aracneui.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

aracneui.o: aracneui.cpp aracneui.h \
		Proxy_Server.hpp \
		ui_aracneui.h \
		HTTP_Request.hpp \
		HTTP_Response.hpp \
		String_Functions.hpp \
		Spider.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o aracneui.o aracneui.cpp

HTML_Parser.o: HTML_Parser.cpp HTML_Parser.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o HTML_Parser.o HTML_Parser.cpp

HTTP_Request.o: HTTP_Request.cpp HTTP_Request.hpp \
		String_Functions.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o HTTP_Request.o HTTP_Request.cpp

HTTP_Response.o: HTTP_Response.cpp HTTP_Response.hpp \
		String_Functions.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o HTTP_Response.o HTTP_Response.cpp

Proxy_Server.o: Proxy_Server.cpp Proxy_Server.hpp \
		HTTP_Request.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Proxy_Server.o Proxy_Server.cpp

Spider.o: Spider.cpp HTML_Parser.hpp \
		Spider.hpp \
		Proxy_Server.hpp \
		HTTP_Request.hpp \
		HTTP_Response.hpp \
		String_Functions.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Spider.o Spider.cpp

String_Functions.o: String_Functions.cpp String_Functions.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o String_Functions.o String_Functions.cpp

moc_aracneui.o: moc_aracneui.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_aracneui.o moc_aracneui.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

